spring:
  data:
    mongodb:
      uri: mongodb://heroku_5207gcmz:cvkjqscebb1n0vrhq3tp9c0t0o@ds135089.mlab.com:35089/heroku_5207gcmz?retryWrites=false
#      uri:

management:
  security:
    enabled: false

  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    env:
      enabled: true
